# error

    Code
      synchronise(do())
    Condition
      Error in `fun()`:
      ! doh

# test throws

    Code
      synchronise(do())
    Condition
      Error in `test()`:
      ! doh

